/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AuthAalLevel = "aal1" | "aal2" | "aal3";

export type AuthCodeChallengeMethod = "plain" | "s256";

export type AuthFactorStatus = "unverified" | "verified";

export type AuthFactorType = "phone" | "totp" | "webauthn";

export type AuthOauthAuthorizationStatus =
  "approved" | "denied" | "expired" | "pending";

export type AuthOauthClientType = "confidential" | "public";

export type AuthOauthRegistrationType = "dynamic" | "manual";

export type AuthOauthResponseType = "code";

export type AuthOneTimeTokenType =
  | "confirmation_token"
  | "email_change_token_current"
  | "email_change_token_new"
  | "phone_change_token"
  | "reauthentication_token"
  | "recovery_token";

export type BaseEnum = "archived" | "draft" | "ready";

export type BaseRunStatus = "completed" | "failed" | "pending" | "running";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
  string,
  bigint | number | string,
  bigint | number | string
>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LlmModelPullStatus = "completed" | "failed" | "pending" | "running";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AiInvocations {
  completed_at: Timestamp | null;
  context_id: string | null;
  context_type: string | null;
  created_at: Generated<Timestamp>;
  error_code: string | null;
  error_message: string | null;
  id: Generated<string>;
  input_tokens: number | null;
  latency_ms: number | null;
  metadata: Generated<Json>;
  model_key: string;
  output_tokens: number | null;
  owner_id: string;
  provider: string;
  request_payload: Generated<Json>;
  response_payload: Json | null;
  run_id: string;
  started_at: Timestamp | null;
  status: Generated<BaseRunStatus>;
  task_type: string;
  total_tokens: number | null;
}

export interface AuthAuditLogEntries {
  created_at: Timestamp | null;
  id: string;
  instance_id: string | null;
  ip_address: Generated<string>;
  payload: Json | null;
}

export interface AuthCustomOauthProviders {
  acceptable_client_ids: Generated<string[]>;
  attribute_mapping: Generated<Json>;
  authorization_params: Generated<Json>;
  authorization_url: string | null;
  cached_discovery: Json | null;
  client_id: string;
  client_secret: string;
  created_at: Generated<Timestamp>;
  discovery_cached_at: Timestamp | null;
  discovery_url: string | null;
  email_optional: Generated<boolean>;
  enabled: Generated<boolean>;
  id: Generated<string>;
  identifier: string;
  issuer: string | null;
  jwks_uri: string | null;
  name: string;
  pkce_enabled: Generated<boolean>;
  provider_type: string;
  scopes: Generated<string[]>;
  skip_nonce_check: Generated<boolean>;
  token_url: string | null;
  updated_at: Generated<Timestamp>;
  userinfo_url: string | null;
}

export interface AuthFlowState {
  auth_code: string | null;
  auth_code_issued_at: Timestamp | null;
  authentication_method: string;
  code_challenge: string | null;
  code_challenge_method: AuthCodeChallengeMethod | null;
  created_at: Timestamp | null;
  email_optional: Generated<boolean>;
  id: string;
  invite_token: string | null;
  linking_target_id: string | null;
  oauth_client_state_id: string | null;
  provider_access_token: string | null;
  provider_refresh_token: string | null;
  provider_type: string;
  referrer: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface AuthIdentities {
  created_at: Timestamp | null;
  /**
   * Auth: Email is a generated column that references the optional email property in the identity_data
   */
  email: Generated<string | null>;
  id: Generated<string>;
  identity_data: Json;
  last_sign_in_at: Timestamp | null;
  provider: string;
  provider_id: string;
  updated_at: Timestamp | null;
  user_id: string;
}

export interface AuthInstances {
  created_at: Timestamp | null;
  id: string;
  raw_base_config: string | null;
  updated_at: Timestamp | null;
  uuid: string | null;
}

export interface AuthMfaAmrClaims {
  authentication_method: string;
  created_at: Timestamp;
  id: string;
  session_id: string;
  updated_at: Timestamp;
}

export interface AuthMfaChallenges {
  created_at: Timestamp;
  factor_id: string;
  id: string;
  ip_address: string;
  otp_code: string | null;
  verified_at: Timestamp | null;
  web_authn_session_data: Json | null;
}

export interface AuthMfaFactors {
  created_at: Timestamp;
  factor_type: AuthFactorType;
  friendly_name: string | null;
  id: string;
  last_challenged_at: Timestamp | null;
  /**
   * Stores the latest WebAuthn challenge data including attestation/assertion for customer verification
   */
  last_webauthn_challenge_data: Json | null;
  phone: string | null;
  secret: string | null;
  status: AuthFactorStatus;
  updated_at: Timestamp;
  user_id: string;
  web_authn_aaguid: string | null;
  web_authn_credential: Json | null;
}

export interface AuthOauthAuthorizations {
  approved_at: Timestamp | null;
  authorization_code: string | null;
  authorization_id: string;
  client_id: string;
  code_challenge: string | null;
  code_challenge_method: AuthCodeChallengeMethod | null;
  created_at: Generated<Timestamp>;
  expires_at: Generated<Timestamp>;
  id: string;
  nonce: string | null;
  redirect_uri: string;
  resource: string | null;
  response_type: Generated<AuthOauthResponseType>;
  scope: string;
  state: string | null;
  status: Generated<AuthOauthAuthorizationStatus>;
  user_id: string | null;
}

export interface AuthOauthClients {
  client_name: string | null;
  client_secret_hash: string | null;
  client_type: Generated<AuthOauthClientType>;
  client_uri: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  grant_types: string;
  id: string;
  logo_uri: string | null;
  redirect_uris: string;
  registration_type: AuthOauthRegistrationType;
  token_endpoint_auth_method: string;
  updated_at: Generated<Timestamp>;
}

export interface AuthOauthClientStates {
  code_verifier: string | null;
  created_at: Timestamp;
  id: string;
  provider_type: string;
}

export interface AuthOauthConsents {
  client_id: string;
  granted_at: Generated<Timestamp>;
  id: string;
  revoked_at: Timestamp | null;
  scopes: string;
  user_id: string;
}

export interface AuthOneTimeTokens {
  created_at: Generated<Timestamp>;
  id: string;
  relates_to: string;
  token_hash: string;
  token_type: AuthOneTimeTokenType;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AuthRefreshTokens {
  created_at: Timestamp | null;
  id: Generated<Int8>;
  instance_id: string | null;
  parent: string | null;
  revoked: boolean | null;
  session_id: string | null;
  token: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface AuthSamlProviders {
  attribute_mapping: Json | null;
  created_at: Timestamp | null;
  entity_id: string;
  id: string;
  metadata_url: string | null;
  metadata_xml: string;
  name_id_format: string | null;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSamlRelayStates {
  created_at: Timestamp | null;
  flow_state_id: string | null;
  for_email: string | null;
  id: string;
  redirect_to: string | null;
  request_id: string;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSchemaMigrations {
  version: string;
}

export interface AuthSessions {
  aal: AuthAalLevel | null;
  created_at: Timestamp | null;
  factor_id: string | null;
  id: string;
  ip: string | null;
  /**
   * Auth: Not after is a nullable column that contains a timestamp after which the session should be regarded as expired.
   */
  not_after: Timestamp | null;
  oauth_client_id: string | null;
  /**
   * Holds the ID (counter) of the last issued refresh token.
   */
  refresh_token_counter: Int8 | null;
  /**
   * Holds a HMAC-SHA256 key used to sign refresh tokens for this session.
   */
  refresh_token_hmac_key: string | null;
  refreshed_at: Timestamp | null;
  scopes: string | null;
  tag: string | null;
  updated_at: Timestamp | null;
  user_agent: string | null;
  user_id: string;
}

export interface AuthSsoDomains {
  created_at: Timestamp | null;
  domain: string;
  id: string;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSsoProviders {
  created_at: Timestamp | null;
  disabled: boolean | null;
  id: string;
  /**
   * Auth: Uniquely identifies a SSO provider according to a user-chosen resource ID (case insensitive), useful in infrastructure as code.
   */
  resource_id: string | null;
  updated_at: Timestamp | null;
}

export interface AuthUsers {
  aud: string | null;
  banned_until: Timestamp | null;
  confirmation_sent_at: Timestamp | null;
  confirmation_token: string | null;
  confirmed_at: Generated<Timestamp | null>;
  created_at: Timestamp | null;
  deleted_at: Timestamp | null;
  email: string | null;
  email_change: string | null;
  email_change_confirm_status: Generated<number | null>;
  email_change_sent_at: Timestamp | null;
  email_change_token_current: Generated<string | null>;
  email_change_token_new: string | null;
  email_confirmed_at: Timestamp | null;
  encrypted_password: string | null;
  id: string;
  instance_id: string | null;
  invited_at: Timestamp | null;
  is_anonymous: Generated<boolean>;
  /**
   * Auth: Set this column to true when the account comes from SSO. These accounts can have duplicate emails.
   */
  is_sso_user: Generated<boolean>;
  is_super_admin: boolean | null;
  last_sign_in_at: Timestamp | null;
  phone: Generated<string | null>;
  phone_change: Generated<string | null>;
  phone_change_sent_at: Timestamp | null;
  phone_change_token: Generated<string | null>;
  phone_confirmed_at: Timestamp | null;
  raw_app_meta_data: Json | null;
  raw_user_meta_data: Json | null;
  reauthentication_sent_at: Timestamp | null;
  reauthentication_token: Generated<string | null>;
  recovery_sent_at: Timestamp | null;
  recovery_token: string | null;
  role: string | null;
  updated_at: Timestamp | null;
}

export interface BaseRun {
  completed_at: Timestamp | null;
  configuration: Generated<Json>;
  created_at: Generated<Timestamp>;
  error_code: string | null;
  error_message: string | null;
  id: Generated<string>;
  owner_id: string;
  prompt: string;
  raw_response: Json | null;
  response: string | null;
  started_at: Timestamp | null;
  status: Generated<BaseRunStatus>;
  updated_at: Generated<Timestamp>;
}

export interface BaseTable {
  base_type: Generated<BaseEnum>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  owner_id: string;
  updated_at: Generated<Timestamp>;
}

export interface CronJob {
  active: Generated<boolean>;
  command: string;
  database: Generated<string>;
  jobid: Generated<Int8>;
  jobname: string | null;
  nodename: Generated<string>;
  nodeport: Generated<number>;
  schedule: string;
  username: Generated<string>;
}

export interface CronJobRunDetails {
  command: string | null;
  database: string | null;
  end_time: Timestamp | null;
  job_pid: number | null;
  jobid: Int8 | null;
  return_message: string | null;
  runid: Generated<Int8>;
  start_time: Timestamp | null;
  status: string | null;
  username: string | null;
}

export interface LlmModelCatalog {
  created_at: Generated<Timestamp>;
  display_name: string;
  enabled: Generated<boolean>;
  id: Generated<string>;
  is_default: Generated<boolean>;
  metadata: Generated<Json>;
  model_key: string;
  owner_id: string;
  provider: string;
  updated_at: Generated<Timestamp>;
}

export interface LlmModelPulls {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  error_code: string | null;
  error_message: string | null;
  gateway_request_id: string | null;
  id: Generated<string>;
  layer_completed_bytes: Int8 | null;
  layer_digest: string | null;
  layer_percent: number | null;
  layer_total_bytes: Int8 | null;
  metadata: Generated<Json>;
  model_key: string;
  owner_id: string;
  progress_status: string | null;
  provider: string;
  started_at: Timestamp | null;
  status: Generated<LlmModelPullStatus>;
  updated_at: Generated<Timestamp>;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  version: string;
}

export interface DB {
  ai_invocations: AiInvocations;
  "auth.audit_log_entries": AuthAuditLogEntries;
  "auth.custom_oauth_providers": AuthCustomOauthProviders;
  "auth.flow_state": AuthFlowState;
  "auth.identities": AuthIdentities;
  "auth.instances": AuthInstances;
  "auth.mfa_amr_claims": AuthMfaAmrClaims;
  "auth.mfa_challenges": AuthMfaChallenges;
  "auth.mfa_factors": AuthMfaFactors;
  "auth.oauth_authorizations": AuthOauthAuthorizations;
  "auth.oauth_client_states": AuthOauthClientStates;
  "auth.oauth_clients": AuthOauthClients;
  "auth.oauth_consents": AuthOauthConsents;
  "auth.one_time_tokens": AuthOneTimeTokens;
  "auth.refresh_tokens": AuthRefreshTokens;
  "auth.saml_providers": AuthSamlProviders;
  "auth.saml_relay_states": AuthSamlRelayStates;
  "auth.schema_migrations": AuthSchemaMigrations;
  "auth.sessions": AuthSessions;
  "auth.sso_domains": AuthSsoDomains;
  "auth.sso_providers": AuthSsoProviders;
  "auth.users": AuthUsers;
  base_run: BaseRun;
  base_table: BaseTable;
  "cron.job": CronJob;
  "cron.job_run_details": CronJobRunDetails;
  llm_model_catalog: LlmModelCatalog;
  llm_model_pulls: LlmModelPulls;
  schema_migrations: SchemaMigrations;
}
